### ISSUE TITLE
when Use arrow keys , no option shown

### ISSUE THREAD

**Issue by nizpew** [ExperiBass/anicli-node#1]
└─[$] <git:(master)> node src/ani-cli.js
? Search Anime: attack on titan
? Choose anime: (Use arrow keys)

/home/*/anicli-node/node_modules/inquirer/lib/prompts/list.js:153
    return this.opt.choices.getChoice(this.selected).value;
                                                    ^

TypeError: Cannot read properties of undefined (reading 'value')
    at ListPrompt.getCurrentValue (/home/*/anicli-node/node_modules/inquirer/lib/prompts/list.js:153:53)
    at /home/*/anicli-node/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
    at OperatorSubscriber._this._next (/home/*/anicli-node/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at Subscriber.next (/home/*/anicli-node/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at /home/*/anicli-node/node_modules/rxjs/dist/cjs/internal/operators/take.js:15:32
    at OperatorSubscriber._this._next (/home/*/anicli-node/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at Subscriber.next (/home/*/anicli-node/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at Interface.handler (/home/*/anicli-node/node_modules/rxjs/dist/cjs/internal/observable/fromEvent.js:59:31)
    at Interface.emit (node:events:529:35)
    at [_onLine] [as _onLine] (node:internal/readline/interface:423:12)

Node.js v18.19.1

**Comment by ExperiBass** [comment]
gogoanime is dead iirc lol
